## Example config file.

# Bot's token.
oauth2_token: ""

# Spice_api credentials
mal_username: ""
mal_password: ""

# Redis data.
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password: null

# SQLALchemy url.
db_url: postgresql://chiru@127.0.0.1/chiru